services:
  web:
    image: docker.io/luubanroi/web:${TAG:-latest}
    networks:
      - navtrack
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - NAVTRACK_API_URL=${NAVTRACK_API_URL:-http://149.28.188.165:3001}
      - NAVTRACK_LISTENER_HOSTNAME=${NAVTRACK_LISTENER_HOSTNAME:-149.28.188.165}
      - NAVTRACK_LISTENER_IP=${NAVTRACK_LISTENER_IP:-149.28.188.165}

  api:
    image: docker.io/luubanroi/api:${TAG:-latest}
    networks:
      - navtrack
    ports:
      - 3001:8080
    restart: unless-stopped
    environment:
      - "MongoOptions__Database=navtrack"
      - "MongoOptions__ConnectionString=mongodb://database"

  listener:
    image: docker.io/luubanroi/listener:${TAG:-latest}
    networks:
      - navtrack
    ports:
      - "7001-7100:7001-7100"
    restart: unless-stopped
    environment:
      - "MongoOptions__Database=navtrack"
      - "MongoOptions__ConnectionString=mongodb://database"

  database:
    image: mongo
    restart: unless-stopped
    networks:
      - navtrack
    volumes:
      - navtrack:/data/db
    # ports:
    #   - 27017:27017

volumes:
  navtrack:

networks:
  navtrack:
